import { localePath, normalizeLocale, type SiteLocale } from '@/config/locale';
import { getLocale } from '@/paraglide/runtime.js';
import { SiteFooter, type FooterColumn } from '@/components/site-footer';

export function Footer({
  locale: localeOverride,
}: { locale?: SiteLocale } = {}) {
  const locale = localeOverride || normalizeLocale(getLocale());
  const copy = {
    en: {
      product: 'Product',
      account: 'Account',
      legal: 'Legal',
      contact: 'Contact',
      tagline:
        'Public video parsing for creators and teams. Use only content you are allowed to process.',
      downloader: 'Downloader',
      transcribe: 'Video to text',
      tools: 'All tools',
      blog: 'Blog',
      api: 'API Docs',
      pricing: 'Pricing',
      faq: 'FAQ',
      signIn: 'Sign in',
      dashboard: 'Dashboard',
      billing: 'Billing',
      userAgreement: 'User Agreement',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      refundPolicy: 'Refund Policy',
      copyright: 'Copyright & Takedown',
      deletion: 'Data deletion request',
      supportEmail: 'Support email',
      supportX: 'Customer support on X',
    },
    zh: {
      product: '产品',
      account: '账户',
      legal: '条款',
      contact: '联系',
      tagline: '面向创作者和团队的公开视频解析工具。请仅处理你有权使用的内容。',
      downloader: '下载工具',
      transcribe: '视频转文字',
      tools: '全部工具',
      blog: '博客',
      api: 'API 文档',
      pricing: '价格',
      faq: '常见问题',
      signIn: '登录',
      dashboard: '账户中心',
      billing: '账单',
      userAgreement: '用户协议',
      privacyPolicy: '隐私政策',
      termsOfService: '服务条款',
      refundPolicy: '退款政策',
      copyright: '版权与下架',
      deletion: '数据删除请求',
      supportEmail: '支持邮箱',
      supportX: 'X 客服',
    },
    es: {
      product: 'Producto',
      account: 'Cuenta',
      legal: 'Legal',
      contact: 'Contacto',
      tagline:
        'Análisis de videos públicos para creadores y equipos. Usa solo contenido que tengas derecho a procesar.',
      downloader: 'Descargador',
      transcribe: 'Video a texto',
      tools: 'Todas las herramientas',
      blog: 'Blog',
      api: 'API',
      pricing: 'Precios',
      faq: 'Preguntas',
      signIn: 'Iniciar sesión',
      dashboard: 'Panel',
      billing: 'Facturación',
      userAgreement: 'Acuerdo de usuario',
      privacyPolicy: 'Política de privacidad',
      termsOfService: 'Términos de servicio',
      refundPolicy: 'Política de reembolso',
      copyright: 'Copyright y retirada',
      deletion: 'Solicitud de eliminación',
      supportEmail: 'Correo de soporte',
      supportX: 'Soporte en X',
    },
    pt: {
      product: 'Produto',
      account: 'Conta',
      legal: 'Legal',
      contact: 'Contato',
      tagline:
        'Análise de vídeos públicos para criadores e equipes. Use apenas conteúdo que você pode processar legalmente.',
      downloader: 'Baixador',
      transcribe: 'Vídeo para texto',
      tools: 'Todas as ferramentas',
      blog: 'Blog',
      api: 'API',
      pricing: 'Preços',
      faq: 'FAQ',
      signIn: 'Entrar',
      dashboard: 'Painel',
      billing: 'Cobrança',
      userAgreement: 'Contrato do usuário',
      privacyPolicy: 'Política de privacidade',
      termsOfService: 'Termos de serviço',
      refundPolicy: 'Política de reembolso',
      copyright: 'Copyright e remoção',
      deletion: 'Solicitação de exclusão',
      supportEmail: 'E-mail de suporte',
      supportX: 'Suporte no X',
    },
    fr: {
      product: 'Produit',
      account: 'Compte',
      legal: 'Juridique',
      contact: 'Contact',
      tagline:
        'Analyse de vidéos publiques pour les créateurs et les équipes. Utilisez uniquement les contenus que vous êtes autorisé à traiter.',
      downloader: 'Téléchargeur',
      transcribe: 'Vidéo en texte',
      tools: 'Tous les outils',
      blog: 'Blog',
      api: 'Documentation API',
      pricing: 'Tarifs',
      faq: 'FAQ',
      signIn: 'Se connecter',
      dashboard: 'Tableau de bord',
      billing: 'Facturation',
      userAgreement: 'Accord utilisateur',
      privacyPolicy: 'Politique de confidentialité',
      termsOfService: 'Conditions d’utilisation',
      refundPolicy: 'Politique de remboursement',
      copyright: 'Droits d’auteur et retrait',
      deletion: 'Demande de suppression',
      supportEmail: 'E-mail d’assistance',
      supportX: 'Assistance sur X',
    },
    de: {
      product: 'Produkt',
      account: 'Konto',
      legal: 'Rechtliches',
      contact: 'Kontakt',
      tagline:
        'Analyse öffentlicher Videos für Creator und Teams. Verarbeite nur Inhalte, für die du die nötigen Rechte hast.',
      downloader: 'Downloader',
      transcribe: 'Video zu Text',
      tools: 'Alle Tools',
      blog: 'Blog',
      api: 'API-Dokumentation',
      pricing: 'Preise',
      faq: 'FAQ',
      signIn: 'Anmelden',
      dashboard: 'Dashboard',
      billing: 'Abrechnung',
      userAgreement: 'Nutzungsvereinbarung',
      privacyPolicy: 'Datenschutzrichtlinie',
      termsOfService: 'Nutzungsbedingungen',
      refundPolicy: 'Rückerstattungsrichtlinie',
      copyright: 'Urheberrecht und Entfernung',
      deletion: 'Antrag auf Datenlöschung',
      supportEmail: 'Support-E-Mail',
      supportX: 'Kundensupport auf X',
    },
    it: {
      product: 'Prodotto',
      account: 'Account',
      legal: 'Note legali',
      contact: 'Contatti',
      tagline:
        'Analisi di video pubblici per creator e team. Usa solo contenuti che hai il diritto di elaborare.',
      downloader: 'Downloader',
      transcribe: 'Video in testo',
      tools: 'Tutti gli strumenti',
      blog: 'Blog',
      api: 'Documentazione API',
      pricing: 'Prezzi',
      faq: 'FAQ',
      signIn: 'Accedi',
      dashboard: 'Dashboard',
      billing: 'Fatturazione',
      userAgreement: 'Accordo utente',
      privacyPolicy: 'Informativa sulla privacy',
      termsOfService: 'Termini di servizio',
      refundPolicy: 'Politica di rimborso',
      copyright: 'Copyright e rimozione',
      deletion: 'Richiesta di eliminazione dati',
      supportEmail: 'E-mail di assistenza',
      supportX: 'Assistenza clienti su X',
    },
    id: {
      product: 'Produk',
      account: 'Akun',
      legal: 'Legal',
      contact: 'Kontak',
      tagline:
        'Pemrosesan video publik untuk kreator dan tim. Gunakan hanya konten yang boleh Anda proses.',
      downloader: 'Pengunduh',
      transcribe: 'Video ke teks',
      tools: 'Semua alat',
      blog: 'Blog',
      api: 'Dokumentasi API',
      pricing: 'Harga',
      faq: 'FAQ',
      signIn: 'Masuk',
      dashboard: 'Dasbor',
      billing: 'Tagihan',
      userAgreement: 'Perjanjian pengguna',
      privacyPolicy: 'Kebijakan privasi',
      termsOfService: 'Ketentuan layanan',
      refundPolicy: 'Kebijakan pengembalian dana',
      copyright: 'Hak cipta dan penghapusan',
      deletion: 'Permintaan penghapusan data',
      supportEmail: 'Email dukungan',
      supportX: 'Dukungan pelanggan di X',
    },
    ja: {
      product: 'プロダクト',
      account: 'アカウント',
      legal: '法務',
      contact: 'お問い合わせ',
      tagline:
        'クリエイターとチーム向けの公開動画解析ツールです。処理する権利のあるコンテンツのみご利用ください。',
      downloader: 'ダウンローダー',
      transcribe: '動画を文字起こし',
      tools: 'すべてのツール',
      blog: 'ブログ',
      api: 'API ドキュメント',
      pricing: '料金',
      faq: 'よくある質問',
      signIn: 'ログイン',
      dashboard: 'ダッシュボード',
      billing: '請求情報',
      userAgreement: 'ユーザー契約',
      privacyPolicy: 'プライバシーポリシー',
      termsOfService: '利用規約',
      refundPolicy: '返金ポリシー',
      copyright: '著作権と削除申請',
      deletion: 'データ削除申請',
      supportEmail: 'サポートメール',
      supportX: 'X カスタマーサポート',
    },
    ko: {
      product: '제품',
      account: '계정',
      legal: '법적 고지',
      contact: '문의',
      tagline:
        '크리에이터와 팀을 위한 공개 동영상 분석 도구입니다. 처리 권한이 있는 콘텐츠만 사용하세요.',
      downloader: '다운로더',
      transcribe: '동영상 텍스트 변환',
      tools: '모든 도구',
      blog: '블로그',
      api: 'API 문서',
      pricing: '요금제',
      faq: '자주 묻는 질문',
      signIn: '로그인',
      dashboard: '대시보드',
      billing: '결제',
      userAgreement: '사용자 계약',
      privacyPolicy: '개인정보 처리방침',
      termsOfService: '서비스 약관',
      refundPolicy: '환불 정책',
      copyright: '저작권 및 삭제 요청',
      deletion: '데이터 삭제 요청',
      supportEmail: '지원 이메일',
      supportX: 'X 고객 지원',
    },
  } as const;
  const t =
    (copy as unknown as Record<string, (typeof copy)['en']>)[locale] || copy.en;
  const localizedHref = (path: string) => localePath(locale, path);
  const columns: FooterColumn[] = [
    {
      title: t.product,
      links: [
        { label: t.downloader, href: localizedHref('/') },
        { label: t.transcribe, href: localizedHref('/transcribe') },
        {
          label: t.tools,
          href: '/tools',
        },
        { label: t.blog, href: localizedHref('/blog') },
        { label: t.api, href: localizedHref('/api-docs') },
        { label: t.pricing, href: localizedHref('/pricing') },
        { label: t.faq, href: localizedHref('/faq') },
      ],
    },
    {
      title: t.account,
      links: [
        { label: t.signIn, href: '/sign-in?callbackUrl=%2F' },
        { label: t.dashboard, href: '/settings' },
        { label: t.billing, href: '/settings/billing' },
      ],
    },
    {
      title: t.legal,
      links: [
        {
          label: t.userAgreement,
          href: localizedHref('/user-agreement'),
        },
        {
          label: t.privacyPolicy,
          href: localizedHref('/privacy-policy'),
        },
        {
          label: t.termsOfService,
          href: localizedHref('/terms-of-service'),
        },
        {
          label: t.refundPolicy,
          href: localizedHref('/refund-policy'),
        },
        {
          label: t.copyright,
          href: localizedHref('/copyright-policy'),
        },
        {
          label: t.deletion,
          href: localizedHref('/data-deletion'),
        },
      ],
    },
    {
      title: t.contact,
      links: [
        {
          label: t.supportEmail,
          href: 'mailto:support@nowatermarkdownloader.com',
          external: true,
        },
        {
          label: t.supportX,
          href: 'https://x.com/MaynorAI1',
          external: true,
        },
      ],
    },
  ];

  return (
    <SiteFooter
      tagline={t.tagline}
      columns={columns}
      socials={[]}
      locale={locale}
    />
  );
}
